version: '3.8'  # specify the version of Docker Compose

services:
  container-and-signature-services:
    container_name: container-and-signature-services
    restart: always
    ports:
      - '86:8092'
    volumes:
      - C:/dev/DMSS-stamping/container-and-signature-services:/confs
    environment:
      - SPRING_CONFIG_LOCATION=/confs/
    image: 'trustlynx/container-signature-service:24.2.0.2'
  digital-stamping-service:
    container_name: digital-stamping-service
    restart: always
    ports:
      - '84:8084'
    volumes:
      - C:/dev/DMSS-stamping/digital-stamping-service:/confs
    environment:
      - SPRING_CONFIG_LOCATION=/confs/
    image: 'trustlynx/dmss-digital-stamping-service:24.0.0.2'
networks:
  default:
